### ISSUE TITLE
Umožnit specifikaci schématu/tabulky

### ISSUE THREAD

**Issue by SmallhillCZ** [kokes/od#122]
Máme databázi, kde máme i jiná data a proto se mi `schéma=modul` a `tabulka=tabulka` nehodí. Potřeboval bych něco jako `schéma=opendata` a `tabulka=modul_tabulka`.

Můžu si to naimportovat do jiné DB a pak nějak přenést, ale to je taková práce navíc. Myslím, že by stačilo jen udělat dvě verze, jednu stávající a jednu jak píšu výše, kde by se název schématu specifikoval argumentem. Něco jako:

```sh
python main.py --partial --connstring postgresql://localhost/postgres --custom_schema opendata
```

Neumím moc Python, tak jsem neposílal hned PR, ale asi to nebude složitý.

**Comment by SmallhillCZ** [comment]
A nebo, jestli by to bylo moc, tak aspoň umožnit schema prefix

**Comment by kokes** [comment]
Ono je to teď takový _past-vedle-pasti_, protože já tam dal ORM, pač chci podporovat víc db (aktuálně SQLite a Postgresu), ALE, ne všechny db podporujou namespaces (schémata)... takže tam mám custom logiku, že pokud db nepodporuje schémata (sqlite), tak se to chová jak píšeš - tabulka=modul_tabulka - zatimco u Postgresy to naplno využívá tu podporu schémat.

Zamyslim se, jestli by tam šel dát nějakej override, kterej by s timhle spolupracoval.

**Comment by SmallhillCZ** [comment]
Jako mně vůbec nevadí ani to druhé jednodušší řešení, že se jen přidá prefix. Koneckonců i v DB kde nemají schémata by to pomohlo. Stejně se tam pak zpravidla řeší schémata prefixem. Typicky MySQL.

**Comment by kokes** [comment]
Jo už tě chápu - udělat prefix cli argument a pak schéma (nebo tabulku, když schéma neumim) pojmenovat `prefix_schema`... to by asi šlo.
