### ISSUE TITLE
[res] číhat a nahrát nový dataset

### ISSUE THREAD

**Issue by kokes** [kokes/od#127]
Měla by to být dvě CSV a celkem dobře strukturovaná, tak čekám celkem málo práce.

**Comment by kokes** [comment]
Bacha, číselníky jsou bohužel zvlášť, takže ty budem muset dojoinovat (jsem pro téměř plnou denormalizaci)

Číselník okresů: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=109&typdat=0&cisjaz=203&format=0
Způsob zániku subjektu: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=572&typdat=0&cisjaz=203&format=2&separator=%2C
Právní forma organizace: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=56&typdat=0&cisjaz=203&format=0
Právní forma (registr osob): https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=149&typdat=0&cisjaz=203&format=0
Kategorie dle počtu pracovníků: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=579&typdat=0&cisjaz=203&format=2&separator=%2C
Klasifikace CZ-NACE: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=80004&typdat=0&cisjaz=203&format=2&separator=%2C
Základní územní jednotky: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=51&typdat=0&cisjaz=203&format=0
Kód institucionálního sektoru: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=5161&typdat=0&cisjaz=203&format=0
Typ čísla domovního: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=73&typdat=0&cisjaz=203&format=2&separator=%2C

Tohle jsou odkazy v XML, ale co jsem zběžně koukal do NKODu, tak jsou i v CSV.

**Comment by MartinCernyCZSO** [comment]
Číselníky ČSÚ jsou primárně zveřejněné na webu (https://apl.czso.cz/iSMS/) s možností stažení **v XML i CSV formátu**.
V NKOD (https://data.gov.cz/datov%C3%A9-sady?poskytovatel=https%3A%2F%2Frpp-opendata.egon.gov.cz%2Fodrpp%2Fzdroj%2Forg%C3%A1n-ve%C5%99ejn%C3%A9-moci%2F00025593&kl%C3%AD%C4%8Dov%C3%A1-slova=%C4%8D%C3%ADseln%C3%ADk) jsou **vybrané číselníky** registrované také v obou formátech.
Odkazy pro přímé stažení uvedených číselníků v CSV jsou tyto:
Číselník okresů: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=109&typdat=0&cisjaz=203&format=2&separator=%2C
Způsob zániku subjektu: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=572&typdat=0&cisjaz=203&format=2&separator=%2C
Právní forma organizace: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=56&typdat=0&cisjaz=203&format=2&separator=%2C
Právní forma (registr osob): https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=149&typdat=0&cisjaz=203&format=2&separator=%2C
Kategorie dle počtu pracovníků: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=579&typdat=0&cisjaz=203&format=2&separator=%2C
Klasifikace CZ-NACE: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=80004&typdat=0&cisjaz=203&format=2&separator=%2C
Základní územní jednotky: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=51&typdat=0&cisjaz=203&format=2&separator=%2C
Kód institucionálního sektoru: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=5161&typdat=0&cisjaz=203&format=2&separator=%2C
Typ čísla domovního: https://apl.czso.cz/iSMS/cisexp.jsp?kodcis=73&typdat=0&cisjaz=203&format=2&separator=%2C

**Comment by kokes** [comment]
První nástřel tu, ale nezavírám, protože ještě nemám pořešené číselníky.

https://github.com/kokes/od/commit/eb0991e8da6269543d63e15d86cc3ddecc188903

**Comment by kokes** [comment]
Číselníky vypadaj dobře, narazil jsem jen na tři problémy.

Konkrétně jde o tyhle kombinace číselníků a hodnot - konkrétně vidim ve sloupci NACE (číselník 80004) občas hodnotu `00`, která ale není v daném číselníku. Podobně je to u 56 a 149 (FORMA a ROSFORMA) a hodnoty 805.


(80004, '00')
(56, '805')
(149, '805')

Takhle vypadaj ty řádky, kterých se to týká (je jich víc, tady jen jedna per chybějící hodnotu):

```
chybi (80004, '00')
{'ICO': '00013846', 'OKRESLAU': 'CZ0712', 'DDATVZN': '1989-08-10', 'DDATZAN': '2021-03-10', 'ZPZAN': '00', 'DDATPAKT': '2021-03-16', 'FORMA': '501', 'ROSFORMA': '501', 'KATPO': '000', 'NACE': '00', 'ICZUJ': '500496', 'FIRMA': 'Polygrafický průmysl Praha, státní podnik - Moravské tiskařské závody, sdružený podnik', 'CISS2010': '11002', 'KODADM': '', 'TEXTADR': 'Olomouc, tř. Lidových milicí 5', 'PSC': '', 'OBEC_TEXT': 'Olomouc', 'COBCE_TEXT': '', 'ULICE_TEXT': '', 'TYPCDOM': '', 'CDOM': '', 'COR': '', 'DATPLAT': '2022-02-28', 'PRIZNAK': ''}
chybi (56, '805')
{'ICO': '75082136', 'OKRESLAU': 'CZ0427', 'DDATVZN': '2006-07-01', 'DDATZAN': '2021-12-31', 'ZPZAN': '00', 'DDATPAKT': '2022-01-18', 'FORMA': '805', 'ROSFORMA': '805', 'KATPO': '210', 'NACE': '84130', 'ICZUJ': '567892', 'FIRMA': 'Regionální rada regionu soudržnosti Severozápad', 'CISS2010': '13130', 'KODADM': '17836701', 'TEXTADR': '', 'PSC': '40001', 'OBEC_TEXT': 'Ústí nad Labem', 'COBCE_TEXT': 'Ústí nad Labem-centrum', 'ULICE_TEXT': 'Berní', 'TYPCDOM': '1', 'CDOM': '2261', 'COR': '1', 'DATPLAT': '2022-02-28', 'PRIZNAK': ''}
chybi (149, '805')
{'ICO': '75082136', 'OKRESLAU': 'CZ0427', 'DDATVZN': '2006-07-01', 'DDATZAN': '2021-12-31', 'ZPZAN': '00', 'DDATPAKT': '2022-01-18', 'FORMA': '805', 'ROSFORMA': '805', 'KATPO': '210', 'NACE': '84130', 'ICZUJ': '567892', 'FIRMA': 'Regionální rada regionu soudržnosti Severozápad', 'CISS2010': '13130', 'KODADM': '17836701', 'TEXTADR': '', 'PSC': '40001', 'OBEC_TEXT': 'Ústí nad Labem', 'COBCE_TEXT': 'Ústí nad Labem-centrum', 'ULICE_TEXT': 'Berní', 'TYPCDOM': '1', 'CDOM': '2261', 'COR': '1', 'DATPLAT': '2022-02-28', 'PRIZNAK': ''}
```

@MartinCernyCZSO můžete na to prosim mrknout, jestli je chybějící řádky v číselnících nebo o překlepy ve faktové tabulce? Díky

**Comment by MartinCernyCZSO** [comment]
Problém identifikován: uvedené kódy v číselnících uvnitř systému ČSÚ existují, ale z určitých (administrativních) důvodů nejsou exportované do veřejných otevřených dat. Oslovil jsem kolegy, kteří to mají na starost, aby se k tomu vyjádřili a byla zajištěna konzistenci dat a kódů v číselnících.

**Comment by MartinCernyCZSO** [comment]
Prozatím informace o použitých kódech:
(80004, '00') = Výroba, obchod a služby neuvedené v přílohách 1 až 3 živnostenského zákona
(56, '805') = Regionální rada regionu soudržnosti
(149, '805') = Regionální rada regionu soudržnosti

Kód 00 není a nebude součástí oficiální klasifikace ekonomických činností (NACE), která je zveřejňovaná podle zákona. Nicméně RES tento kód pro některé záznamy používá...
Vytvořím a zveřejním samostatný **číselník ekonomických činností pro RES**, který bude položku s kódem 00 obsahovat.

Kódy 805 mají ukončenou platnost a jsou použité pouze pro zaniklé subjekty.
Současný export číselníků z aplikace iSMS generuje pouze položky platné k určenému dni (defaultně aktuální den v době stažení). Připravím vlastní řešení, které bude z číselníků ČSÚ exportovat všechny položky, které kdy byly platné, aby byly dostupné pro otevřená data i položky s ukončenou platností.

Dejte mi prosím pár dní na vyvinutí alternativních exportů z číselníků ČSÚ pro potřeby otevřených dat.

**Comment by kokes** [comment]
@MartinCernyCZSO super, díky za rychlou reakci, na řešení nijak nespěchám.

**Comment by kokes** [comment]
@MartinCernyCZSO můžu se zeptat, zda jste s tím nějak pohli? Abych věděl, jestli mám aktualizovat kód s novými klasifikátory nebo to obejít nějakou kličkou. Díky

**Comment by MartinCernyCZSO** [comment]
Omlouvám se, že to trvá déle, než jsem očekával.
Uvedené kódy a jejich významy platí, ale do otevřených dat jsem to ještě nedostal z technických a organizačních důvodů. Pokusím se to posunout v rozhodovacím procesu a zveřejnit co nejdříve.

**Comment by MartinCernyCZSO** [comment]
Následující číselníky a klasifikace v CSV formátu včetně dříve chybějících položek jsou zveřejněny na nových URL adresách:
- číselník 56: https://vdb.czso.cz/opendata/ciselniky/polozky?kod=56
- číselník 149: https://vdb.czso.cz/opendata/ciselniky/polozky?kod=149
- klasifikace NACE (80004) pro RES: https://vdb.czso.cz/opendata/ciselniky/polozky?kod=CZ_NACE_RES

Zítra se tyto URL ke stažení CSV souborů promítnou i do Národního katalogu OD.

**Comment by kokes** [comment]
Super, funguje!
