### ISSUE TITLE
Problémy na windows

### ISSUE THREAD

**Issue by jindroush** [kokes/od#162]
Zkouším dnes prvně, existující issues jsem prohledal, a nenašel jsem žádný podobný problém.

Zatím jsem stahoval "ares", tam je problém s tím, že na Windows s mandatory lockingem nelze do tempu vytvořeným NamedTemporaryFile zapisovat v dalším řádku. Řešení je použít (Delete=false) a pak ten temporary file mazat někde po zpracování. Co s tím? Dát tam výhybku pro Win větev, nebo to předělat na všech OS na to Delete, nebo jak? Pravidla pro to, jak daný patch předat / testy jsem neobjevil.

Druhý problém mám s "zakazky", tam mi to zhavaruje na Keyerror, tam jsem ještě příčinu nezjistil (ale budu pátrat, možná i přepínat):
 ```
 File "E:\projekty\2022_04_21_statni_data\data\zakazky\main.py", line 144, in main
    tp = tblmap[hd]  # document type
KeyError: ('Přehled zakázek z eTržišť',)
```
EDIT: Ano, stačilo v otevírání mapping.json přidat encoding="utf-8", to havaruje o kousek dál na zpracování datumu, pátrání pokračuje (už jen těch nečekaně dlouhých řádek je tam nečekaně mnoho ;) )

Windows 10, 64bit, eng, poslední build. Python 3.6.7.

**Comment by kokes** [comment]
Dobré odpoledne, problém se zakázkami na Windows je mi znám (#85), minule jsem to vyřešil jako vy - přidáním explicitního encodingu při otevírání souborů. Bohužel jsem od té doby opět trochu driftoval a nemálo souborů tento hint opět nemá. Přidal jsem to v rámci https://github.com/kokes/od/pull/163, ještě to prohlédnu a mergnu.

Co se týče NamedTemporaryFile, tak to teď z hlavy nevím. Intuitivně mě napadá udělat ten soubor v současném adresáři, kde by zápisová práva neměla být problém, ale zkusím pogooglit, jestli existuje lepší řešení.

**Comment by jindroush** [comment]
```
szif
====
Traceback (most recent call last):
  File "E:\projekty\od\main.py", line 86, in <module>
    module(outdir, partial=args.partial)
  File "E:\projekty\od\data\szif\main.py", line 53, in main
    zf = ZipFile(tmpf.name)
  File "C:\Python36\lib\zipfile.py", line 1113, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\X\\AppData\\Local\\Temp\\tmplqn8ttxr'
```

Problém je Windows mandatory locking - podle toho, co jsem vygooglil, NamedTemporaryFile otevře soubor pro zápis, a jakmile pak následující funkce chce otevřít ten stejný soubor pro zápis jménem (nikoli přes handle), tak to už kvůli lockování nelze. Radili dvě věci, mode='w' mi nefungovalo, Delete=false mi fungovalo, ale pak se tam musí dodělat explicitní mazání toho tempu.

Ares: chyba stejná jako výše
Szif: chyba výše
Volby: fungují, tam je to použito lehce jinak?

**Comment by jindroush** [comment]
Tak ares/main.py z branche funguje ok, nekontroloval jsem ovšem, jestli si po sobě uklidil.

**Comment by kokes** [comment]
Super, díky. V mezičase jsem upravil i szif a volby (ty volby vám možná fungovaly, protože kód s NamedTemporaryFile se volá až po asi 30 sekundách), tak jestli byste prosím zkusil všechny tři datasety z té branche. Úplně jsem smazal NamedTemporaryFile a použil místo toho TemporaryDirectory, ve které si pak explicitně vytvářím soubory - nečekám, že by Windows měly nějaké zamykání na úrovni adresářů.

**Comment by jindroush** [comment]
```
szif
====
Traceback (most recent call last):
  File "E:\projekty\od\main.py", line 86, in <module>
    module(outdir, partial=args.partial)
  File "E:\projekty\od\data\szif\main.py", line 92, in main
    element.clear()
  File "C:\Python36\lib\tempfile.py", line 809, in __exit__
    self.cleanup()
  File "C:\Python36\lib\tempfile.py", line 813, in cleanup
    _shutil.rmtree(self.name)
  File "C:\Python36\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python36\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Python36\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\X\\AppData\\Local\\Temp\\tmpdxzy5s1u\\tmp.zip'
```

**Comment by kokes** [comment]
Jo, tady nesprávně spoléhám na garbage collection a jeho uvolňování file handlerů (což na Windows nefunguje). Chtěl jsem to opravit už před časem, ale teď mám konečně dobrý důvod. Commitnul jsem změnu, snad už to bude v pořádku.

(A píšu si, že bych měl opět rozjet CI nad Windows workery, protože jinak se k Windows stroji nedostanu.)

**Comment by jindroush** [comment]
Volby a ares jsou vyřešeny, ale netuším, zda nedělám něco se szif špatně, protože ta chyba je stále stejná, i když si myslím, že mám poslední verzi. Teď jsem si vzal ten fix.

**Comment by kokes** [comment]
Tak jsem pro szif zkusil opravit snad poslední místo, kde by mohlo dojít k zamykání. Pokud ani to nevyjde, tak budu muset sehnat nějakou Windows stanici a opravit to interaktivně.

**Comment by jindroush** [comment]
Teď už szif proleze.
Vytvořená data mají 30KB a 4KB csv, pokud to je správně, tak se tenhle tiket dá asi zavřít.

**Comment by kokes** [comment]
Super. Ty zakázky od MMR budem řešit vedle.
