### ISSUE TITLE
[czechinvest] problem

### ISSUE THREAD

**Issue by jindroush** [kokes/od#167]
Opět je třeba explicitně přidat encoding u otvírání mapping.json a slovnik.csv

Poté to vyhlásí něco, že si mám sosnout to XLS - proč si ho nevezme ten skript sám - mění se url?

A potom
```

czechinvest
===========
Traceback (most recent call last):
  File "E:\projekty\2022_04_21_statni_data\main.py", line 86, in <module>
    module(outdir, partial=args.partial)
  File "E:\projekty\2022_04_21_statni_data\data\czechinvest\main.py", line 76, in main
    (j, val, hd1[j]) for j, val in enumerate(mapping["hd1"]) if val != hd1[j]
AssertionError: []
```
Tam si zatím nejsem přesně jist, co se tam assertuje.

Stále na Windows 10 eng. Jsem se rozhodl, že když už se v tom vrtám, že postupně projdu všechno, aby to bylo nějak v jednom čase konzistentní.

**Comment by kokes** [comment]
1. encoding je upraven, to jsem dělal včera
2. ano, URL se mění, takže se to musí dělat ručně
3. Assertuje se tam, že se schéma toho souboru nemění (bohužel se občas mění), mrknu na to
