### ISSUE TITLE
[dotinfo] vyžaduje Python 3.7

### ISSUE THREAD

**Issue by jindroush** [kokes/od#168]
Prosím o přidání checku na začátek, plus případně fix requirements v dokumentaci

import sys
assert sys.version_info >= (3, 7)

funkce date.fromisoformat je až ve verzi 3.7

**Comment by jindroush** [comment]
Totéž platí pro iissp

**Comment by kokes** [comment]
1. Python 3.6 je už EOL, takže mě nějak netrápí, že ho už nepodporuju.
2. Upravím dokumentaci, aby to tam bylo explicitní (uvádim tam nesprávně 3.6+)
