### ISSUE TITLE
[eufondy] windows locking problem

### ISSUE THREAD

**Issue by jindroush** [kokes/od#169]
Podle mého stejný problém jako dříve - do tempu je stažen xlsx soubor, otevřen, a pak se temp snaží uklidit dřív, než je xlsx soubor zavřen.
Tj. řádek 142 a dále. Domnívám se, že z logiky kódu by ty dva with statementy měly být vnořeny, nikoli za sebou.

```
eufondy
=======
Traceback (most recent call last):
  File "E:\projekty\2022_04_21_statni_data\main.py", line 86, in <module>
    module(outdir, partial=args.partial)
  File "E:\projekty\2022_04_21_statni_data\data\eufondy\main.py", line 276, in main
    prehled_2017_2013(outdir, partial)
  File "E:\projekty\2022_04_21_statni_data\data\eufondy\main.py", line 145, in prehled_2017_2013
    wb = load_workbook(target_filename, read_only=True)
  File "C:\Python36\lib\tempfile.py", line 809, in __exit__
    self.cleanup()
  File "C:\Python36\lib\tempfile.py", line 813, in cleanup
    _shutil.rmtree(self.name)
  File "C:\Python36\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python36\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Python36\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\x\\AppData\\Local\\Temp\\tmpvythnfs1\\workbook.xlsx'
```

**Comment by kokes** [comment]
Hmmm, na unixu mi to funguje, na Windows se to asi agresivněji snaží promazat dočasný adresář. Asi jsem předpokládal, že `load_workbook` je eager, takže mu smazání vadit nebude, ale asi to tak nebude, zanořím.

**Comment by jindroush** [comment]
To je rozdíl v chování linux/windows - v linuxu lze smazat takto otevřený soubor, ve windows ne. A ten soubor se maže, když se ukončí ten první with blok - proto je třeba to vnoření, nebo with se dvěmi "as", ale to nevím, zda zde lze takto zřetězit.

(Jinak toto je poslední nefunkční věc kvůli windows, zbytek jsem prověřil a funguje, díky)

**Comment by kokes** [comment]
V pull requestu odkázaném výše jsem to celé zanořil, tak to snad pomůže.

**Comment by jindroush** [comment]
Zkusil jsem, nefungovalo. Zkusil jsem přidat wb.Close na správné místo, nefungovalo. Pořád je tam nějaký problém s mazáním v nesprávnou chvíli.
Nakonec pomohlo jen vyhodit read_only=True z load_workbook, pak to funguje.

**Comment by kokes** [comment]
Podle mě jsem to už vyřešil, `python3 main.py eufondy` mi na Windows Server 2019 seběhne v pohodě, ale nevím, jestli tahle OS verze nemá jiné řešení lockování než Windows 10/11.

**Comment by jindroush** [comment]
Potvrzuji, teď už to chodí.
(Teda nevím, co Pythonu udělá, když ten url_open vytimeoutuje a raw tím pádem bude prázdný...)
PS: Server 2019 by měl být postavený na jednom z buildů Windows 10, takže z hlediska testování by se to mělo chovat velmi podobně.
