### ISSUE TITLE
Eu fondy - programové období 2021

### ISSUE THREAD

**Issue by suchoss** [kokes/od#256]
Ahoj,

netušíš, jestli EU fondy už mají otevřená data od "2021"? Koukal jsem, že na stránkách už mají přidáno nové programové období:
https://www.dotaceeu.cz/cs/evropske-fondy-v-cr/kohezni-politika-po-roce-2020

Díky

**Comment by suchoss** [comment]
Tak jsem dostal od nich odpověď

> Sestava Seznam operací 2021-2027 prochází aktuálně posledním testováním (správnost načítání dat, objem dat se oproti 2014-2020 rozrostl). Začátkem února by měly být seznamy zveřejněny na webu ve formátu xls. Hned následně dořešíme formát open dat a jejich umístění.

**Comment by kokes** [comment]
Super! Sorry, měl jsem tu otevřenej tab celou dobu - já to právě hledal asi týden před tebou, a nic jsem nenašel, tak jsem se pak na základě tohodle ptal v pátek jedný analytičky, a taky nic neměla. A teď díky tý odpovědi vim proč.

Tak snad udržej strukturu.

**Comment by kokes** [comment]
Hotovo v #269.
