### ISSUE TITLE
[eufondy] seznam projektu z MS2021+

### ISSUE THREAD

**Issue by kokes** [kokes/od#303]
Tak oni nakonec udelali XML data i pro 2021-2027

https://ms21opendata.mssf.cz

**Comment by kokes** [comment]
Hm, ta struktura je uplne jina a je to cely samozrejme bez dokumentace.

**Comment by suchoss** [comment]
Ahoj, co jsem se včera díval, tak struktura:
[https://ms14opendata.mssf.cz/SeznamProjektu.xml](https://ms14opendata.mssf.cz/SeznamProjektu.xml)
je stejná jako struktura
[https://ms21opendata.mssf.cz/SeznamOperaci_21_27.xml](https://ms21opendata.mssf.cz/SeznamOperaci_21_27.xml)

Nebo mi něco uniklo? Při rychlém projití souboru jsem nenašel moc rozdílů... Nebo změnili ms14 pod rukama. Každopádně dokumentace ale nesedí. Nechápu jejich rozdělení platby do dvou položek...

**Comment by kokes** [comment]
Tak ne, museli to upravit, protoze ta dokumentace tam v zari nebyla (ne ze by k necemu byla).

**Comment by suchoss** [comment]
Jo, ta dokumentace je neúplná a prakticky k ničemu
