### ISSUE TITLE
Zpracovat data Justice

### ISSUE THREAD

**Issue by kokes** [kokes/od#45]
https://dataor.justice.cz/

Pozor:
- jak je zakódován aktuální název subjektu?
- jak zjistit seznam všech datasetů
- je to nekomprimované, tak to bude trvat věčnost
- iterativní xml parse bude třeba, jako vždy
- data narození jsou zatim špatně

**Comment by kokes** [comment]
Moje otázky na justici:

- data nejsou komprimovaná - ať už po cestě nebo jako soubor
- neni nikde listing všech souborů
- chybí XSD pro ta XML
- datum je vždy špatně (CE[S]T)
- `<udaje>` jsou nestrukturované - člověk musí podle hlavičky zjistit, co je co - nechcete to nějak zanořit?
- to CSV je vlastně zbytečné, nikdo to nenaparsuje
- v XML jsou jakoby JSON, ale nejsou to JSON (chybí uvozovky)

Qs:
- když chci úplná data, můžu prostě brát jen 2019 vždy?

**Comment by Cactucs** [comment]
Zkoušel jsem večera parsovat úplný výpis spolků (Praha, 2019). Poznámky co k tomu mám teď (zatím neřeším sémantiku jen syntax)

V XML je u nějakých subjektů uvnitř "JSON dat" nevalidní "znaky" (je tam to co znám jako HTML entity a mému parseru se to nelíbí, jsou za koncem těch dat).

**Comment by kokes** [comment]
Jo, to sem musel obejít přes nějaké failure recovery v parseru, jinak bych taky skončil. Přidal sem to na seznam.

**Comment by Cactucs** [comment]
Pár poznámek k tomu co jsem dál zjistil (dataset: úplný, spolky, Praha, 2019, XML): 

- datum je tvaru `YYYY-MM-DD 22:00:00.0 UTC`, kde místo `22` může být ještě `23` (často u výmazů) nebo `00` (často u datumů narození) - [vysvětlení](https://twitter.com/kondrej/status/1113438809218277376)
- `<hlavicka>` uvnitř `<Udaj>` má různé hodnoty (viz https://pastebin.com/GBs29mYe - vždy název a za tím počet - celkem je v mém datasetu 31040 subjektů, ale některé tam mají něco dvakrát, protože něco je už vymazaný údaj). 
- Vůbec nechápu o čem píše [uživatelská příručka](https://dataor.justice.cz/files/ISVR_OpenData_Uzivatelska_prirucka.pdf) - má tam nějaké povinné a volitelné atributy. Například povinný atribut `UCEL_SUBJEKTU`  (což snad je `Účel`) je u méně než 42 % subjektů. 

No celé je to od strukturovaných dat dost daleko. 😞

**Comment by kokes** [comment]
Hm, já se dneska snažil zagregovat různé hlavičky podle jejich schématu (např. různí statutárové mají různé hlavičky, ale stejné schéma), že bych pro ně měl shodné mapování, které bych si vygeneroval ze všech existujících polí (když nám nedaj XSD).

Jenže taky jsem narazil na stovky distinktních hlaviček. Takže napřed napíšu do justice, jestli ty hlavičky nechtěj kategorizovat, protože s takhle vysokou kardinalitou se nedá pracovat.

[first.ipynb.gz](https://github.com/kokes/od/files/3050640/first.ipynb.gz)

**Comment by Cactucs** [comment]
Co je to co bys chtěl vidět? Chápu to dobře, že pro tebe je zajímavé vědět "tato FO/PO má něco společného s tímhle IČO"?

**Comment by kokes** [comment]
Mimo jiné. Chci ta data rozparsovat po vzoru ARESu, takže co typ objektu, to tabulka. Už jsem psal do Justice, tak uvidíme. https://github.com/kokes/od/blob/master/data/ares/api/init.sql

**Comment by Cactucs** [comment]
Tak právě jsem zjistil, že v datasetu 2019, Praha, akciové společnosti nemají 3 subjekty IČO. Jde o `MONTINVEST, a.s. - organizační složka`, `Polytechna, podnik zahraničního obchodu pro zprostředkování technické spolupráce` a `Československá akciová společnost pro mezinárodní zasilatelství- zkráceně METRANS`, takže já nedokážu ani napárovat dva subjekty z různých exportů (resp. když si něco naimportuju, tak potom nedokážu udělat upsert). - To IČO evidentně nemají vůbec.

**Comment by Cactucs** [comment]
A občas je tam místo textu nebo "jsonu" jenom `CLOB` místo větších textů - např. u [této společnosti](https://or.justice.cz/ias/ui/rejstrik-firma.vysledky?subjektId=306510&typ=UPLNY) jde o všechny vymazané `Ostatní skutečnosti`. 

Na ty "jsony" se mi snad podařilo napsat parser, ale není to úplně triviální, protože čárky nejenom oddělují fieldy (resp. ukončují hodnotu), ale také můžou být uvnitř v té hodnotě bez žádného escapování.

**Comment by kokes** [comment]
Na ty JSONy bych se vyprdnul, to prostě není JSON a nehodlám psát parser na nějaký pseudoformát. Reportoval jsem to jako chybu, tak uvidíme, snad se s tím nějak poperou.

Obecně bych do toho nevěnoval moc úsilí v tuhle chvíli, protože je netriviální šance, že se to ještě změní.

**Comment by kokes** [comment]
Přišlo mi pár odpovědí z MSp, ještě se doptávám na podrobnosti a pak to nějak sepíšu. Něco jsou svolní změnit, něco jsme trochu vyřešili (např. seznam souborů je v nedokumentovaném API).

**Comment by kokes** [comment]
Odložim si tady kód pro získání všech datasetů z webu, bude to časem dokumentované přímo od Justice, viz další komentář.

```python
from datetime import date
import requests

# package_list a package_list_compact se asi lisi - ten nekompaktni endpoint nejde filtrovat??? Tak to asi udelame na klientovi
year = date.today().year
# url_pl = 'https://dataor.justice.cz/api/3/action/package_list?q=year%3A{}%3Bformat%3AXML%3Btype%3AFULL'.format(year)
url_pl = 'https://dataor.justice.cz/api/3/action/package_list'

r = requests.get(url_pl)
assert r.ok
dt = r.json()
assert dt['success']

dss = [ds for ds in dt['result'] if ds.endswith('-{}'.format(year)) and '-full-' in ds]

urls = []
for ds in dss:
    url = 'https://dataor.justice.cz/api/3/action/package_show?id={}'.format(ds)
    r = requests.get(url)
    assert r.ok
    dtp = r.json()
    assert dtp['success']
    ds_url = [j['url'] for j in dtp['result']['resources'] if j['format'] == 'text/xml']
    assert len(ds_url) == 1
    urls.append(ds_url[0])
```

**Comment by kokes** [comment]
1. Kde je kontakt na kurátora?
   - Kontakt je u každé datové sady, je to: dataor@msp.justice.cz

2. Kde získám seznam všech datových sad?
   - Jde to přes API pomocí endpointu `package_list` a `package_show`, endpointy budou v budoucnosti dokumentované.

3. Bude existovat XSD schéma?
   - Ano, bude.

4. Všude je špatné datum/čas.
   - Berou na vědomí.

5. Data nejsou komprimovaná.
   - Berou na vědomí.

6. JSONy nejsou JSON
   - Bude to XML.

7. Občas dojde k chybě při parsování XML kvůli nedovoleným znakům.
   - Bude opraveno.

8. Chybí typy elementů, k dispozici je jen hlavička.
   - Berou na vědomí.

9. Jak zjistím, kdy byl záznam dané firmy aktualizován?
   - Dotaz neformulován úplně šťastně, takže jsem nedostal úplnou odpověď.

10. Jak můžu získat všechny subjekty? Včetně těch zaniklých.
    - ~Nestačí full-2019 datasety, nebudou tam zaniklé subjekty, ty budou v datových sadách z roku zápisu té firmy - ale tyhle datasety ještě nejsou publikované.

11. Víceméně variace na otázku 8, vyřešeno odpovědí na ní.

12. Některé datasety neexistují, např. evrhzs-full-brno-2019.xml - jde o opomenutí, nebo prostě žádná taková firma není?
    - Žádná taková firma není. Řeší to bod 2, kdy získám seznam všech existujících datasetů.

**Comment by janaslo** [comment]
Díky za info!

K zaniklým subjektům: koukala jsem se do těch starších (full) datasetů a vypadá to, že v nich jsou záznamy subjektů, které v daném roce aspoň chvíli existovaly. Takže např. v datasetu z roku 2016 jsou i takové, které v tom roce zanikly, v datasetu z roku 2017 pak už nejsou.

**Comment by kokes** [comment]
@janaslo supr, dík - a co se týče záznamů, který jsou v obou dumpech, tak ty informace jsou stejné? Jen přemejšlim, jak nejlíp shromáždit všechna data - jestli člověk musí jít nějak chronologicky, nebo jestli stačí prostě zprocesit data za všechny roky a jen si držet nějakou hashmapu se zprocesovanejma IČ a pokud na ně narazim znova, tak je přeskočim - tohle bude fungovat za předpokladu, že firma 123 bude mít stejnej záznam v dumpu z 2016 i 2019.

Problém pochopitelně je, že nic nekomprimují, takže bude trvat věčnost to celé stáhnout.

**Comment by janaslo** [comment]
Ke stažení všech mi přijde rozumné:

- průběžně zpracovávat jen soubory za současný rok (i to je slušný objem, nějaké změnovky by byly super ...)
- ty starší stáhnout v podstatě jen jednou (od nejnovějšího k nejstaršímu) a vytáhnout z nich subjekty zaniklé v daném roce

V tomhle duchu jsem si to teď zkusila na menším vzorku, šla jsem od 2019 do minulosti. Dotahovala jsem ty co nemám - u předchozích let to opravdu byly samé zaniklé - a u těch ostatních kontrolovala, jestli jsou stejné. Tam se občas (malé jednotky procent) objevily rozdíly, hlavně ohledně statutárů. Zatím jsem nezkoumala, jestli jsou tam opravdu jiná data, nebo třeba jen jinak zapsaná. I kdyby tam rozdíly opravdu byly, předpokládala bych, že platí novější verze (tj. ta, kterou už mám).

**Comment by kokes** [comment]
Ach ta malá vítězství, kontaktní bod je nyní v patičce ❤️ 

![Screenshot 2019-05-20 at 15 11 20](https://user-images.githubusercontent.com/8451755/58024061-a1292700-7b11-11e9-8d22-f44a850ddb2f.png)

**Comment by kokes** [comment]
Pro orientaci jsem si vytáhl velikosti těch souborů. Jestli dobře počítám, tak všechny letošní fully maj 9 giga, všechny fully za celou historii 60 giga.

https://gist.github.com/kokes/23d2c7b02e7ee7544095d38be19688a6

**Comment by kokes** [comment]
Abych lépe věděl, na čem jsme, stáhnul jsem si všechny fully z historii a trochu je rozparsoval.  Nakonec stačil jeden silnější stroj, kód si tady zase zálohuju pro budoucí referenci.

Stažení:
```python
import os
from datetime import date
from multiprocessing import Pool
from urllib.parse import urlparse
from urllib.request import urlretrieve
import requests


def get_urls():
    # package_list a package_list_compact se asi lisi - ten nekompaktni endpoint nejde filtrovat??? Tak to asi udelame na klientovi
    year = date.today().year
    # url_pl = 'https://dataor.justice.cz/api/3/action/package_list?q=year%3A{}%3Bformat%3AXML%3Btype%3AFULL'.format(year)
    url_pl = 'https://dataor.justice.cz/api/3/action/package_list'

    r = requests.get(url_pl)
    assert r.ok
    dt = r.json()
    assert dt['success']

    # dss = [ds for ds in dt['result'] if ds.endswith('-{}'.format(year)) and '-full-' in ds]
    dss = [ds for ds in dt['result'] if '-full-' in ds]

    urls = []
    for ds in dss:
        url = 'https://dataor.justice.cz/api/3/action/package_show?id={}'.format(ds)
        r = requests.get(url)
        assert r.ok
        dtp = r.json()
        assert dtp['success']
        ds_url = [j['url'] for j in dtp['result']['resources'] if j['format'] == 'text/xml']
        assert len(ds_url) == 1
        
        yield ds_url[0]

def dl(url):
    dr = 'data'
    fn = urlparse(url).path.rpartition('/')[-1]
    urlretrieve(url, os.path.join(dr, fn))

    return fn

with Pool(16) as p:
    for fn in p.imap_unordered(dl, get_urls()):
        print(fn)
```

Vysekání základních informací
```python
import os
import csv
import gzip
from glob import glob
from datetime import date, timedelta
from multiprocessing import Pool

from tqdm import tqdm
import lxml.etree

os.makedirs('csv', exist_ok=True)

def parse(fn):
    tfn = fn.replace('data/', 'csv/').replace('.xml', '.csv')
    cfn = fn.replace('data/', '')
    with open(tfn, 'w', encoding='utf8') as fw:
        cw = csv.writer(fw)
        cw.writerow(['fn', 'ico', 'nazev', 'platnost_od', 'platnost_do', 'udaju'])
        with open(fn, 'rb') as f:
            n = 0
            parser = lxml.etree.iterparse(f, recover=True)

            for part, element in parser:
                if not (part == 'end' and element.tag == 'Subjekt'): continue
                ico = getattr(element.find('ico'), 'text', None)
                if not ico:
                    continue

                nazev = getattr(element.find('nazev'), 'text')
                od = getattr(element.find('zapisDatum'), 'text')
                od = date.fromisoformat(od[:10]) + timedelta(days=1)
                do = getattr(element.find('vymazDatum'), 'text', None)
                if do:
                    do = date.fromisoformat(do[:10]) + timedelta(days=1)
                udaje = len(element.findall('./udaje/Udaj'))

                cw.writerow([cfn, ico, nazev, od, do, udaje])

                element.clear()

    return fn

if __name__ == '__main__':
    fns = glob('data/*.xml')
    mb = 1024*1024
    sizes = round(sum(os.path.getsize(j) for j in fns)/mb)

    progress = tqdm(total=sizes)
    with Pool(16) as p:
        for fn in p.imap_unordered(parse, fns):
            size = round(os.path.getsize(fn)/mb, 1)
            progress.update(size)
```

pg schéma
```sql
create schema if not exists justice;
create table justice.stats (
	fn varchar not null,
	ico bigint not null,
	nazev varchar not null,
	platnost_od date not null,
	platnost_do date,
	udaju smallint not null
);
```

a finální shell skript

```sh
for fn in csv/*.csv.gz; do
	echo $fn
	gunzip -c $fn | psql -c 'copy justice.stats from stdin csv header'
done
```

**Comment by kokes** [comment]
Je tam necelých 5 milionů záznamů, vidim tam pár věcí:

1. Asi se potvrzuje to, cos psala - @janaslo, musíme jít do minulosti, abychom tam tu firmu našli, ALE

2. Nemůžem to dělat úplně paralelně, protože když jako "dataset" označím (právní forma, soud), tak existuje 500 firem, které patří do více takových datasetů. Jde o firmy, které změnily právní formu (a ta stará forma, zdá se, "zanikla"):

![Screen Shot 2019-05-21 at 21 06 09](https://user-images.githubusercontent.com/8451755/58124071-a075bb00-7c0d-11e9-9216-1b835add5bd7.png)

Ale taky firmy, které změnily soud, pod kterým jsou zapsané:

![Screen Shot 2019-05-21 at 21 07 27](https://user-images.githubusercontent.com/8451755/58124104-b2eff480-7c0d-11e9-8eaf-e402dc46507d.png)

**Comment by kokes** [comment]
Docela jsem to rozpracoval v rámci mergnutýho PR #67, takže tohle zavírám a přesouvám dodělávky do milestone: https://github.com/kokes/od/milestone/1
