### ISSUE TITLE
psp/steno/psp.py na windows 10

### ISSUE THREAD

**Issue by michalblaha** [kokes/od#84]
hazi chybu 

Traceback (most recent call last):
  File "psp.py", line 23, in <module>
    for ln in f:
  File "C:\Users\Michal\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 328: character maps to <undefined>

Pomáhá změnit přidat errors='ignore' na řádek 22.
with open('pozice.txt', errors='ignore') as f:

**Comment by kokes** [comment]
Hele místo errors=ignore tam dej `encoding='utf8'`, protože takhle ti to nesprávně odseká ty jejich pozice.

Tohle je dlouhodobej problém na Windows a mám v plánu to upravit u více skriptů napříč repem.
