### ISSUE TITLE
Chyba parsovani steno - chybi posledni zaznam schuze

### ISSUE THREAD

**Issue by michalblaha** [kokes/od#89]
viz rok 2017, schuze 15.

v s015013.htm zacina mluvit Stanjura, mluvi dlouze az na s015014, kde slove prebira Okamura a dava hlasovat. Pote schuzi ukoncuje. 

V CSV chybi Okamurovo posledni vystoupeni po Stajnurovi z s015014.htm.

**Comment by kokes** [comment]
Máš recht, nepěknej bug, kterej přežil příliš dlouho, hned commitnu fix.
