### ISSUE TITLE
[Cedr] špatné párování

### ISSUE THREAD

**Issue by suchoss** [kokes/od#94]
Ahoj, u Cedru nesedí tohle:
{
    "url": "ciselnikCedrOperacniProgramv01.csv.gz",
    "id": "idOperacniProgram",  >> mělo by být **id**
    "nazev": "operacniProgramNazev" >> mělo by být **programNazev**
  },
{
    "url": "ciselnikMmrOperacniProgramv01.csv.gz",
    "id": "idOperacniProgram",
    "nazev": "operacniProgramNazev"
  }

**Comment by kokes** [comment]
Čau, proč myslíš? Koukal jsem teď to toho CSV a ty moje sloupce tam jsou

![Screen Shot 2020-02-04 at 17 04 40](https://user-images.githubusercontent.com/8451755/73762621-b2ce5f80-4770-11ea-9284-0ecb62f1617f.png)

**Comment by suchoss** [comment]
Aha, už to vidím. Překoukl jsem se. Porovnával jsem to s **ciselnikprogramv01** , tam je ta struktura jiná. 

Omlouvám se.
