### ISSUE TITLE
eufondy/excely

### ISSUE THREAD

**Issue by suchoss** [kokes/od#97]
Ahoj,

v eufondech při zpracování excelu - mám pocit, že používáš špatný soubor (ten soubor je jen s posledním přírůstkem). 
https://github.com/kokes/od/blob/af4de59c02b498fc41086812a9062c3eff5182b1/data/eufondy/excely/fondy0713.py#L2
https://github.com/kokes/od/blob/af4de59c02b498fc41086812a9062c3eff5182b1/data/eufondy/excely/fondy0713.py#L12

správný odkaz na kompletní soubor by měl být tady:
https://dotaceeu.cz/Dotace/media/SF/Informace%20o%20%c4%8derp%c3%a1n%c3%ad/Seznamy%20p%c5%99%c3%adjemc%c5%af%20(List%20of%20Beneficiaries)/P%c5%99ehled%20projekt%c5%af/Prehled_projektu_20160603upraveno.xlsx

(je to ten poslední odkaz dole viz obrázek)
![image](https://user-images.githubusercontent.com/39336141/74659786-3d618680-5195-11ea-82a3-83843c9e6617.png)

Navíc dle jejich podpory existuje ještě jeden soubor s daty do roku 2006
https://www.dotaceeu.cz/cs/evropske-fondy-v-cr/programove-obdobi-2004-2006-(1)/vysledky-cerpani

**Comment by kokes** [comment]
1. Ne, nejsou to poslední přírůstky, oni vydávali full dump každý měsíc. Rozdíl v těch dvou datasetech je mírný - seznam příjemců a přehled projektů jsou dva různé datasety. Už teď z hlavy nevím, proč jsem vybral seznam příjemců, ale měl jsem dobrý důvod. Jeden z datasetů má mnohem lepší popis projektů, ten druhý má lepší informace o příjemcích (myslím, že ten můj). Jo a mají různý počet unikátních IČ, protože jeden z datasetů má úřady práce kategorizované jinak než ten druhý, bacha na to. Takže ne, nemám špatný dataset, jen používám jiný :-)
2. O 2004-2006 trochu vim, ale nikdy jsem s tím nepracoval, protože v tom datasetu chybí IČ a já to nechtěl párovat podle jména.

**Comment by suchoss** [comment]
Aha, koukám na to. Myslel jsem, že jsou to přírůstky, protože je velikostně daleko menší. V tom co jsem posílal jsou duplicity - hodně.

Jo, s doplněním IČ to bude zajímavé.

Díky
